package webhook
package webhook

import (
























































































































}	}		t.Fatalf("Unexpected error: %v", resp.Error)	if resp.Error != nil {	resp := sender.Send(req)	}		Payload: map[string]interface{}{"test": "data"},		Method: "PUT",		URL:    testServer.URL,	req := Request{	sender := NewSender(5 * time.Second)	defer testServer.Close()	}))		w.WriteHeader(http.StatusOK)		}			t.Errorf("Expected PUT, got %s", r.Method)		if r.Method != "PUT" {	testServer := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {func TestSend_CustomHTTPMethod(t *testing.T) {}	}		t.Error("Expected error for invalid URL")	if resp.Error == nil {	resp := sender.Send(req)	}		Payload: map[string]interface{}{"test": "data"},		Method: "POST",		URL:    "http://invalid-nonexistent-domain.test:99999",	req := Request{	sender := NewSender(5 * time.Second)func TestSend_InvalidURL(t *testing.T) {}	}		t.Errorf("Expected response body, got %s", string(resp.Body))	if string(resp.Body) != `{"error": "server error"}` {	}		t.Errorf("Expected status 500, got %d", resp.StatusCode)	if resp.StatusCode != http.StatusInternalServerError {	}		t.Fatalf("Unexpected error: %v", resp.Error)	if resp.Error != nil {	resp := sender.Send(req)	}		Payload: map[string]interface{}{"test": "data"},		Method: "POST",		URL:    testServer.URL,	req := Request{	sender := NewSender(5 * time.Second)	defer testServer.Close()	}))		w.Write([]byte(`{"error": "server error"}`))		w.WriteHeader(http.StatusInternalServerError)	testServer := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {func TestSend_ErrorResponse(t *testing.T) {}	}		t.Fatalf("Unexpected error: %v", resp.Error)	if resp.Error != nil {	resp := sender.Send(req)	}		Payload: map[string]interface{}{"test": "data"},		// Method omitted, should default to POST		URL: testServer.URL,	req := Request{	sender := NewSender(5 * time.Second)	defer testServer.Close()	}))		w.WriteHeader(http.StatusOK)		}			t.Errorf("Expected default method POST, got %s", r.Method)		if r.Method != "POST" {	testServer := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {func TestSend_DefaultMethod(t *testing.T) {}	}		t.Errorf("Expected status 200, got %d", resp.StatusCode)	if resp.StatusCode != http.StatusOK {	}		t.Fatalf("Unexpected error: %v", resp.Error)	if resp.Error != nil {	resp := sender.Send(req)	}		},			"test": "data",		Payload: map[string]interface{}{		Method: "POST",		URL:    testServer.URL,	req := Request{	sender := NewSender(5 * time.Second)	defer testServer.Close()	}))		w.WriteHeader(http.StatusOK)		}			t.Errorf("Expected Content-Type application/json, got %s", r.Header.Get("Content-Type"))		if r.Header.Get("Content-Type") != "application/json" {		}			t.Errorf("Expected POST, got %s", r.Method)		if r.Method != "POST" {	testServer := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {	receivedPayload := make(map[string]interface{})func TestSend_Success(t *testing.T) {)	"time"	"testing"	"net/http/httptest"	"net/http"